version: "3.8"
services:
  api:
    build:
      context: ../bizzy-api/
      dockerfile: dockerfile
    ports:
      - "8080:3002"
      - "9229:9229"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ../bizzy-api/:/app
      - /app/node_modules
    command: sh -c "cd lambdas/home && serverless offline start"
  db:
    image: mongo:3.6.20-xenial
    ports:
      - "27017:27017"
    expose:
      - 27017
    command: >
      bash -c "mongod && show dbs"
  # www:
  #   build:
  #     context: ../bizzy/
  #     dockerfile: dockerfile
  #   volumes:
  #     - '../bizzy/:/app'
  #     - '/app/node_modules'
  #   ports:
  #     - 3001:3000
  #   depends_on:
  #     - api
  #     - db
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
