version: "3.8"
services:
  api:
    build:
      context: ../bizzy-api-monolith/
      dockerfile: dockerfile
    ports:
      - "5000:3002"
      - "9229:9229"
    env_file:
      - .env
    volumes:
      - ../bizzy-api-monolith/:/app
      - /app/node_modules
    command: npm start
    depends_on:
      - db
  app:
    build:
      context: ../bizzy/
      dockerfile: dockerfile
    volumes:
      - '../bizzy/:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    depends_on:
      - api
    environment:
      - CHOKIDAR_USEPOLLING=true
  www:
    build:
      context: ../www/
      dockerfile: dockerfile
    volumes:
      - '../www/:/www'
      - '/www/node_modules'
    ports:
      - 8080:8080
    environment:
      - CHOKIDAR_USEPOLLING=true
  db:
    container_name: "db"
    image: mongo:4
    ports:
      - "27017:27017"
    expose:
      - 27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: